language: node_js

node_js:
  - 4.2.2

after_success:
  - codecov --file coverage/lcov.info --disable search

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

sudo: false

before_install:
  - pip install --user codecov
  - $CXX --version
  - if [ "$TRAVIS_NODE_VERSION" = "0.8" ]; then npm install -g npm@2.7.3; fi;
